name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build for ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: time-app
            asset_name: time-app-linux-x86_64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: time-app.exe
            asset_name: time-app-windows-x86_64.exe
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: time-app
            asset_name: time-app-macos-x86_64
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: time-app
            asset_name: time-app-macos-aarch64

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
        target: ${{ matrix.target }}

    - name: Install Linux dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libxkbcommon-dev libssl-dev

    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2

    - name: Build
      run: cargo build --release --target ${{ matrix.target }}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.asset_name }}
        path: target/${{ matrix.target }}/release/${{ matrix.artifact_name }}

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download Linux artifact
      uses: actions/download-artifact@v4
      with:
        name: time-app-linux-x86_64
        path: ./time-app-linux-x86_64
    
    - name: Download Windows artifact
      uses: actions/download-artifact@v4
      with:
        name: time-app-windows-x86_64.exe
        path: ./time-app-windows-x86_64.exe
    
    - name: Download macOS x86_64 artifact
      uses: actions/download-artifact@v4
      with:
        name: time-app-macos-x86_64
        path: ./time-app-macos-x86_64
    
    - name: Download macOS aarch64 artifact
      uses: actions/download-artifact@v4
      with:
        name: time-app-macos-aarch64
        path: ./time-app-macos-aarch64
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref }}
        name: Release ${{ github.ref }}
        draft: false
        prerelease: false
        files: |
          ./time-app-linux-x86_64/time-app|time-app-linux-x86_64
          ./time-app-windows-x86_64.exe/time-app.exe|time-app-windows-x86_64.exe
          ./time-app-macos-x86_64/time-app|time-app-macos-x86_64
          ./time-app-macos-aarch64/time-app|time-app-macos-aarch64